### ISSUE TITLE
Not a real issue. Just a place to store images that can be referenced in README's etc.

### ISSUE THREAD

**Issue by remarcmij** [HackYourFuture/JavaScript1#16]
![image](https://user-images.githubusercontent.com/2788771/32167430-1beebf9e-bd69-11e7-9680-fbf5c9f6681b.png)
![image](https://user-images.githubusercontent.com/2788771/32170525-282ff208-bd75-11e7-9a45-8d6975804fdd.png)

**Comment by mkruijt** [comment]
hi @remarcmij , if you want to add images to a review, makeme or readme file you can just add a "assets" folder in the specific week, like we did here: https://github.com/HackYourFuture/JavaScript/tree/master/Week1

**Comment by mkruijt** [comment]
oh and I saw somewhere you had a written something about map/filter/reduce, would you like to add that to the review of week7?

**Comment by remarcmij** [comment]
Yeah, Maartje, these diagrams were in preparation for that, but I will create assets instead.
