### ISSUE TITLE
new link for good understanding promises 

### ISSUE THREAD

**Issue by jalalalwani** [HackYourFuture/JavaScript1#25]
hi @mkruijt , i have read this article and i found it very nice for good understanding promises specially for beginners .
https://scotch.io/tutorials/javascript-promises-for-dummies

**Comment by mkruijt** [comment]
hi @jalalalwani , please fork the repository, add the link to the readme file of the corresponding week and make a pull request

**Comment by prakharcipher** [comment]
Is this still open? I'd like to add it.

**Comment by mkruijt** [comment]
Hi @jalalalwani if you make a PR we can actually add it. you know how to do this, also check my previous comment

**Comment by jalalalwani** [comment]
Sure @mkruijt, i gonna do it now.
