### ISSUE TITLE
Step 4: Async challenge improved description

### ISSUE THREAD

**Issue by ynaut** [HackYourFuture/JavaScript1#43]
First and foremost I just want to say really great work with the module 👍 😃 

On to the issue

I found the problem description a bit confusing.  Specifically what is meant by  "Rewrite the code below to Async"? 
Are you supposed to wrap the code snippets into functions that return a Promise? 

A clearer description would be really appreciated by a confused mentor trying to explain to the students what they are supposed to do 😄

**Comment by gijscor** [comment]
@ynaut I think you are not referring to the JavaScript module 1, where we don't talk about promise so I will close this issue. Would be great if you could tell me what module you are referring to specifically, so we can have a look at it. Thanks!

**Comment by ynaut** [comment]
@gijscor The content has completely changed since I posted this, so it's not relevant anymore. The new JS curriculum looks really nice though!

**Comment by gijscor** [comment]
@ynaut thanks!
