### ISSUE TITLE
link trouble

### ISSUE THREAD

**Issue by acimanx** [HackYourFuture/JavaScript1#51]
https://github.com/HackYourFuture/JavaScript1/blob/master/Week2/MAKEME.md

**103 line link doesn't work.**
`6\.1 Declare an empty array. Make sure that the name you choose indicates 'plurality', because an array is capable of containing more than one element. (See [Naming conventions](../fundamentals/naming_conventions.md)).  
`

**Comment by profxed** [comment]
@acimanx Thanks for your Issue I am working on it.
